### ISSUE TITLE
1.20.6 Porting Checklist

### ISSUE THREAD

**Issue by Caltinor** [Caltinor/Project-MMO-2.0#520]
Items to test/confirm before releasing at new 1.21 alpha on 1.20.6
- [x] Itemstack req data properly loads and displays
- [x] Inventory stats render properly
- [x] Stat Scroll Widget
  - [x] mob effects list properly
  - [x] items list properly
- [x] vein crosshair displays
- [x] salvage hint overlay renders properly
- [x] skill list renders properly
- [x] levelup unlocks list properly
- [x] location data properly loads bonuses
- [x] Object Data loads:
  - [x] reqs
  - [x] xp
  - [x] bonuses
- [x]  common and client configs load all properties
- [x] server configs load from file and sync to clients
- [x] Config reset on reload properly clears existing settings
- [x] item NBT properly passed to NBT systems
- [x] enchantment reqs apply to items
- [x] pos/neg effects apply as intended
- [x] Attribute perks properly apply modifiers
- [x] Creative reach properly toggles
- [x] Enchant/smelt event stack output to perks is valid
- [x] consume event properly detects food
- [x] brew event brewed tracking works
- [x] AutoValue entity attributes properly calculated
- [x] AutoItem food properly identified
- [x] AutoItem tool/armor properties properly applied with new Tier changes
- [x] Fireworks generate properly
- [x] Loot modifiers proc
- [x] Mob Scaling applies modifiers correctly
- [x] Generally networking is working
- [x] Feature packs generate and load
- [x] Overlays render
- [x] Data generators generate properly
- [x] PSD loads and saves properly
- [x] Gain list fading
- [x] Inventory Skill list xp to next level not showing progress.
- [x] genData withConfigs should imply withDefaults.
- [x] withDefaults properly grabs other datapack values
